"""Add latest_bolo

Revision ID: efc3724009d5
Revises: 1ffe71dfaa74
Create Date: 2021-02-10 16:30:47.698780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'efc3724009d5'
down_revision = '1ffe71dfaa74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('latest_bolo', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'latest_bolo')
    # ### end Alembic commands ###
